# Generated by Django 3.2.7 on 2021-11-01 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_account_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('question', models.TextField()),
                ('options', models.TextField()),
            ],
            options={
                'unique_together': {('title', 'question', 'options')},
            },
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('decision', models.CharField(max_length=500)),
                ('property_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.member')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
            options={
                'unique_together': {('property_no', 'question')},
            },
        ),
    ]
