# Generated by Django 3.2.7 on 2021-11-01 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_account_email'),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voting',
            options={'verbose_name_plural': 'Voting'},
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.TextField(verbose_name='Options'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(verbose_name='Decision'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='decision',
            field=models.CharField(max_length=500, verbose_name='Decision'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='property_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.member', verbose_name='Property No.'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question', verbose_name='Question'),
        ),
    ]
