# Generated by Django 3.2.7 on 2021-11-03 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('polls', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='property_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.member', verbose_name='Property No.'),
        ),
    ]
