# Generated by Django 3.2.7 on 2021-10-23 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking_lot', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='property_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.member', verbose_name='Property No.'),
        ),
        migrations.AddField(
            model_name='gate_log',
            name='parking_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='parking_lot.parking', verbose_name='Parking ID'),
        ),
        migrations.AddField(
            model_name='gate_log',
            name='property_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.member', verbose_name='Property No.'),
        ),
    ]
