# Generated by Django 3.2.7 on 2021-10-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate_log',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('2-wheeler', '2-wheeler'), ('4-wheeler', '4-wheeler')], max_length=25, null=True, verbose_name='Vehicle Type'),
        ),
    ]
