# Generated by Django 3.2.7 on 2021-11-18 09:44

from django.db import migrations, models
import staff.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_Staff',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('occupation', models.CharField(max_length=50, verbose_name='Occupation')),
                ('image', models.ImageField(upload_to=staff.models.upload_personal, verbose_name='Staff Image')),
            ],
            options={
                'verbose_name': 'Personal Staff',
                'verbose_name_plural': 'Personal Staff',
                'ordering': ['s_no'],
            },
        ),
        migrations.CreateModel(
            name='Society_Staff',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('occupation', models.CharField(max_length=50, verbose_name='Occupation')),
                ('aadhaar', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Aadhaar No.')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('salary', models.IntegerField(verbose_name='Salary')),
                ('work_place', models.CharField(max_length=50, verbose_name='Works in')),
                ('from_place', models.CharField(max_length=50, verbose_name='Comes from')),
                ('mobile_no', models.CharField(max_length=10, verbose_name='Mobile No.')),
                ('image', models.ImageField(upload_to=staff.models.upload_society, verbose_name='Staff Image')),
            ],
            options={
                'verbose_name': 'Society Staff',
                'verbose_name_plural': 'Society Staff',
                'ordering': ['s_no'],
            },
        ),
    ]
