# Generated by Django 3.2.7 on 2021-11-02 03:36

from django.db import migrations, models
import staff.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_Staff',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('occupation', models.CharField(max_length=50, verbose_name='Occupation')),
                ('image', models.ImageField(upload_to=staff.models.upload_personal, verbose_name='Staff Image')),
            ],
            options={
                'verbose_name_plural': 'Personal_Staff',
                'ordering': ['s_no'],
            },
        ),
    ]
