# Generated by Django 3.2.7 on 2021-11-02 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('society_info', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Property Address or Staff Occupation')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Joined On')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('property_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.account', verbose_name='Property No.')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('mobile_no', models.CharField(max_length=50, verbose_name='Mobile No.')),
                ('tenant_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tenant Name')),
                ('tenant_mobile', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tenant Mobile No.')),
                ('property_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='society_info.property_info', verbose_name='Property Type')),
            ],
            options={
                'ordering': ['property_no'],
            },
        ),
    ]
