# Generated by Django 3.2.7 on 2021-11-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.DateField(editable=False, verbose_name='For the Month')),
                ('amount_basic', models.IntegerField(blank=True, verbose_name='Basic')),
                ('amount_paid', models.IntegerField(default=0, verbose_name='Paid')),
                ('amount_penalty', models.IntegerField(editable=False, verbose_name='Penalty')),
                ('amount_due', models.IntegerField(editable=False, verbose_name='Due')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenance',
                'ordering': ['-month', 'property_no'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='Date and Time')),
                ('amount', models.IntegerField(verbose_name='Transaction Amount')),
                ('option', models.CharField(choices=[('paid', 'Paid'), ('received', 'Received')], max_length=15, verbose_name='Paid/Recieved')),
                ('to', models.CharField(max_length=50, verbose_name='To/From')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
