# Generated by Django 3.2 on 2021-10-20 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('property_no', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Property Number')),
                ('property_type', models.CharField(max_length=30, null=True, verbose_name='Property Type')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('mobile_no', models.CharField(max_length=50, verbose_name='Mobile Number')),
                ('tenant_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tenant Name')),
                ('tenant_mobile', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tenant Mobile')),
            ],
        ),
        migrations.CreateModel(
            name='parking',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Parking Slot id')),
                ('filled', models.BooleanField(choices=[('F', 'Filled'), ('E', 'Empty')], verbose_name='Status')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security_gate.member')),
            ],
        ),
        migrations.CreateModel(
            name='gate_log',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False, verbose_name='Serial Number')),
                ('name', models.CharField(max_length=50, verbose_name='Name of the ENtry Person')),
                ('entry', models.DateTimeField(verbose_name='Entry time')),
                ('exit', models.DateTimeField(verbose_name='Exit time')),
                ('vehicle_type', models.CharField(max_length=20, verbose_name='Vehicle type')),
                ('vehicle_number', models.CharField(max_length=10, verbose_name='Vehicle Number')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='security_gate.parking')),
                ('property_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security_gate.member', verbose_name='Property Number')),
            ],
        ),
    ]
