# Generated by Django 3.2 on 2021-10-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_gate', '0002_auto_20211020_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate_log',
            name='exit',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Exit time'),
        ),
    ]
