# Generated by Django 3.2 on 2021-10-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_gate', '0003_alter_gate_log_exit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate_log',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name of the Entry Person'),
        ),
    ]
