# Generated by Django 3.2 on 2021-10-22 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security_gate', '0005_alter_parking_filled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate_log',
            name='parking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security_gate.parking'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Parking Slot id'),
        ),
    ]
