# Generated by Django 3.2 on 2021-10-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_gate', '0007_alter_gate_log_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate_log',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Vehicle Number'),
        ),
    ]
