# Generated by Django 3.2 on 2021-10-25 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security_gate', '0008_alter_gate_log_vehicle_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate_log',
            name='parking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='security_gate.parking'),
        ),
    ]
