# Generated by Django 3.2 on 2021-10-29 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_gate', '0009_alter_gate_log_parking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate_log',
            name='entry',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Entry time'),
        ),
        migrations.AlterField(
            model_name='gate_log',
            name='exit',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Exit time'),
        ),
    ]
