# Generated by Django 3.2.7 on 2021-10-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time')),
                ('author', models.CharField(max_length=25, verbose_name='Announcement Made by')),
                ('category', models.CharField(choices=[('Notification', 'Notification'), ('Voting Result', 'Voting Result'), ('Complaint', 'Complaint')], max_length=25, verbose_name='Category')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('item', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Inventory Item')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventory Items',
                'ordering': ['item'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.DateField(editable=False, verbose_name='For the Month')),
                ('amount_basic', models.IntegerField(blank=True, verbose_name='Basic')),
                ('amount_paid', models.IntegerField(default=0, verbose_name='Paid')),
                ('amount_penalty', models.IntegerField(editable=False, verbose_name='Penalty')),
                ('amount_due', models.IntegerField(editable=False, verbose_name='Due')),
                ('payment_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date of Payment')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenance',
                'ordering': ['-month', 'property_no'],
            },
        ),
        migrations.CreateModel(
            name='Property_Info',
            fields=[
                ('property_type', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Property Type')),
                ('maintenance', models.IntegerField(verbose_name='Maintenance Amount')),
                ('covered_area', models.IntegerField(verbose_name='Covered Area')),
            ],
            options={
                'verbose_name': 'Property Info',
                'verbose_name_plural': 'Properties',
                'ordering': ['property_type'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time')),
                ('amount', models.IntegerField(verbose_name='Transaction Amount')),
                ('option', models.CharField(choices=[('paid', 'Paid'), ('received', 'Received')], max_length=15, verbose_name='Paid/Recieved')),
                ('to', models.CharField(max_length=50, verbose_name='To/From')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
