# Generated by Django 3.2.7 on 2021-10-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society_info', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='payment_date',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(verbose_name='Date and Time'),
        ),
    ]
