# Generated by Django 3.2.7 on 2021-11-02 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='property_no',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.member', verbose_name='Property No.'),
        ),
        migrations.AlterUniqueTogether(
            name='maintenance',
            unique_together={('property_no', 'month')},
        ),
    ]
