# Generated by Django 3.2.7 on 2021-10-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society_staff',
            name='Aadhar',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='society_staff',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
