# Generated by Django 3.2.7 on 2021-10-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211013_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='society_staff',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='personal_staff',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='personal_staff',
            name='occupation',
            field=models.CharField(max_length=50, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='society_staff',
            name='Aadhar',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Aadhar Card'),
        ),
        migrations.AlterField(
            model_name='society_staff',
            name='From',
            field=models.CharField(max_length=50, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='society_staff',
            name='mobile',
            field=models.CharField(max_length=10, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='society_staff',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='society_staff',
            name='occupation',
            field=models.CharField(max_length=50, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='society_staff',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='society_staff',
            name='workplace',
            field=models.CharField(max_length=50, verbose_name='Workplace'),
        ),
    ]
