# Generated by Django 3.2.7 on 2021-10-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211019_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal_staff',
            options={'verbose_name': 'Personal_Staff', 'verbose_name_plural': 'Personal_Staffs'},
        ),
        migrations.AlterModelOptions(
            name='society_staff',
            options={'verbose_name': 'Society_Staff', 'verbose_name_plural': 'Society_Staffs'},
        ),
        migrations.AddField(
            model_name='personal_staff',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='photos/Personal', verbose_name='Person image'),
        ),
        migrations.AlterField(
            model_name='society_staff',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='photos/Society', verbose_name='Person image'),
        ),
    ]
