# Generated by Django 3.2.7 on 2021-10-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211019_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society_staff',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='photos/Society'),
        ),
    ]
