# Generated by Django 3.2.7 on 2021-10-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_society_staff_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society_staff',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
