# Generated by Django 3.2.7 on 2021-10-19 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_society_staff_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='society_staff',
            old_name='img',
            new_name='image',
        ),
    ]
