# Generated by Django 3.2.7 on 2021-10-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_img_society_staff_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='society_staff',
            name='AadharPhoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
