# Generated by Django 3.2.7 on 2021-10-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_society_staff_aadharphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_staff',
            name='img',
        ),
        migrations.AddField(
            model_name='personal_staff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
