# Generated by Django 3.2.7 on 2021-10-20 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20211020_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal_staff',
            old_name='Sno',
            new_name='sno',
        ),
    ]
