# Generated by Django 3.2.7 on 2021-10-20 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_sno_personal_staff_sno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal_staff',
            old_name='sno',
            new_name='Sno',
        ),
        migrations.RenameField(
            model_name='society_staff',
            old_name='AadharPhoto',
            new_name='aadharimage',
        ),
    ]
