# Generated by Django 3.2.7 on 2021-10-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20211020_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='society_staff',
            name='aadharimage',
        ),
    ]
