# Generated by Django 3.2.7 on 2021-10-23 20:45

from django.db import migrations, models
import django.db.models.deletion
import staff.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Society_Staff',
            fields=[
                ('occupation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.account', verbose_name='Occupation')),
                ('aadhaar', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Aadhaar No.')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('salary', models.IntegerField(verbose_name='Salary')),
                ('work_place', models.CharField(max_length=50, verbose_name='Works in')),
                ('from_place', models.CharField(max_length=50, verbose_name='Comes from')),
                ('mobile_no', models.CharField(max_length=10, verbose_name='Mobile No.')),
                ('image', models.ImageField(upload_to=staff.models.upload_society, verbose_name='Staff Image')),
            ],
            options={
                'verbose_name_plural': 'Society_Staff',
                'ordering': ['occupation'],
            },
        ),
    ]
