# Generated by Django 3.2.7 on 2021-11-18 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='property_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.member', verbose_name='Property No.'),
        ),
        migrations.AddField(
            model_name='voting',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question', verbose_name='Question'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('title', 'question', 'options')},
        ),
        migrations.AlterUniqueTogether(
            name='voting',
            unique_together={('property_no', 'question')},
        ),
    ]
