# Generated by Django 3.2.5 on 2021-10-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(max_length=16, verbose_name='property number')),
                ('month', models.DateField()),
                ('basic', models.IntegerField(verbose_name='amount basic')),
                ('due', models.IntegerField(verbose_name='amount due')),
            ],
            options={
                'verbose_name': 'maintenance',
                'verbose_name_plural': 'maintenance',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('received_from', models.CharField(max_length=64, verbose_name='from')),
                ('sent_to', models.CharField(max_length=64, verbose_name='to')),
                ('description', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
            },
        ),
    ]
