# Generated by Django 3.2.5 on 2021-10-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_month_maintenance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='paid',
            field=models.IntegerField(default=0, verbose_name='amount paid'),
        ),
        migrations.AlterUniqueTogether(
            name='maintenance',
            unique_together={('property', 'date')},
        ),
    ]
