# Generated by Django 3.2.5 on 2021-10-18 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20211018_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='date',
            new_name='datetime',
        ),
    ]
