# Generated by Django 3.2.5 on 2021-10-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_rename_date_transaction_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(verbose_name='when'),
        ),
    ]
