# Generated by Django 3.2.5 on 2021-10-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_transaction_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='penalty',
            field=models.IntegerField(default=0),
        ),
    ]
