# Generated by Django 3.2.5 on 2021-10-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_maintenance_penalty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='received_from',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sent_to',
        ),
        migrations.AddField(
            model_name='transaction',
            name='choices',
            field=models.CharField(choices=[('send', 'send'), ('receive', 'receive')], default='send', max_length=7),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_from',
            field=models.CharField(default='', max_length=64, verbose_name='to/from'),
        ),
    ]
